baseURL = "https://nanjakorewa.github.io/MemoryRecipes/"
title = "Hearth Recipes"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true
enableRobotsTXT = true
sectionPagesMenu = "main"
timeZone = "Asia/Tokyo"

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"

[params]
  BookTheme = "auto"
  BookLogo = "images/logo.png"
  BookDateFormat = "2006-01-02"
  BookSearch = true
  BookToC = true
  BookPortableLinks = true
  BookSection = "*"
  description = "Multilingual foil-friendly recipes inspired by Japanese home cooking"
  [params.firebase]
    apiKey = "AIzaSyArcBO_f03k2W88KwhnCZdZZGC1Jgj0Tec"
    authDomain = "vizir-512e4.firebaseapp.com"
    projectId = "vizir-512e4"
    appId = "1:540232784402:web:52912b65b611a65275d6cb"
    storageBucket = "vizir-512e4.firebasestorage.app"
    messagingSenderId = "540232784402"
    measurementId = "G-HWKKPKW829"

[languages]
  [languages.ja]
    weight = 1
    title = "\u6696\u7089\u30ec\u30b7\u30d4"
    languageName = "\u65e5\u672c\u8a9e"
    contentDir = "content/ja"
    [languages.ja.params]
      description = "\u716e\u7269\u3084\u713c\u304d\u7269\u306a\u3069\u3001\u624b\u9806\u304c\u898b\u3084\u3059\u3044\u591a\u8a00\u8a9e\u30ec\u30b7\u30d4\u96c6"
      BookSection = "ja"

  [languages.en]
    weight = 2
    title = "Hearth Recipes"
    languageName = "English"
    contentDir = "content/en"
    [languages.en.params]
      description = "Japanese-inspired home cooking for busy weeknights"
      BookSection = "en"

[outputs]
  home = ["HTML", "RSS"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    ordered = true
    endLevel = 3
    startLevel = 2
